import { useEffect, useState } from 'react'
import { doc, onSnapshot } from 'firebase/firestore'
import { db, DEMO_MODE } from '../firebase'
import { useAppConfig } from '../hooks/useAppConfig'
import { OCTOPUS_IMG } from './OctopusMark'

const DEMO_LINE = '👑 רונן ל. בפסגה — אבל הלילה הכול יכול להתהפך.\n😅 חצי מכם ניחשו 1-0… יצירתיות, יש לכם?\n🔥 3 משחקים גדולים היום — בהצלחה!'

// Amos & Avigdor's signature catchphrase — always shown on the home pundit card.
const CATCHPHRASE = 'בראש של יוסי ושל מנש אני לא משקר'

/** עמוס ואביגדור's daily AI recap ("Anchor Desk"), generated by the pundit job. */
export default function PunditCard() {
  const cfg = useAppConfig()
  const [text, setText] = useState<string>(DEMO_MODE ? DEMO_LINE : '')
  const [preview, setPreview] = useState<string>(DEMO_MODE ? 'המשחק הגדול של היום: ברזיל נגד ארגנטינה — תתכוננו לדרמה! 🔥' : '')
  const [imgBroken, setImgBroken] = useState(false)

  useEffect(() => {
    if (DEMO_MODE) return
    return onSnapshot(doc(db, 'appState', 'pundit'), (s) => {
      setText((s.data()?.text as string) || '')
      setPreview((s.data()?.preview as string) || '')
    })
  }, [])

  if (!cfg.features.pundit) return null

  return (
    <div
      className="glass"
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: 12,
        padding: '14px 16px',
        background: 'linear-gradient(135deg, color-mix(in srgb, var(--color-primary) 12%, var(--color-bg-elevated)), var(--color-bg-elevated))'
      }}
    >
      {/* Header: framed photo + title */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        {!imgBroken ? (
          <img
            src={OCTOPUS_IMG}
            alt="עמוס ואביגדור"
            onError={() => setImgBroken(true)}
            style={{
              width: 84,
              height: 56,
              objectFit: 'cover',
              objectPosition: '50% 35%',
              borderRadius: 'var(--radius-md)',
              border: '2px solid color-mix(in srgb, var(--color-primary) 55%, var(--color-border-strong))',
              boxShadow: '0 4px 14px rgba(0,0,0,0.25)',
              flexShrink: 0
            }}
          />
        ) : (
          <span style={{ fontSize: 34, flexShrink: 0 }}>🎲</span>
        )}
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 11, color: 'var(--color-text-muted)', fontWeight: 700 }}>🎙️ עמוס ואביגדור · ניתוח AI</div>
          <div
            style={{
              fontFamily: 'var(--font-display)',
              fontSize: 13,
              fontWeight: 800,
              color: 'var(--color-primary)',
              marginTop: 2,
              lineHeight: 1.3
            }}
          >
            «{CATCHPHRASE}»
          </div>
        </div>
      </div>

      {/* Daily recap */}
      {text && <div style={{ fontWeight: 600, fontSize: 14, lineHeight: 1.7, whiteSpace: 'pre-line' }}>{text}</div>}

      {/* Today's preview */}
      {preview && (
        <div style={{ paddingTop: text ? 8 : 0, borderTop: text ? '1px solid var(--glass-border)' : 'none', fontSize: 13, fontWeight: 700 }}>
          🔮 תחזית היום: {preview}
        </div>
      )}
    </div>
  )
}
