import { useEffect, useState } from 'react'
import { doc, onSnapshot } from 'firebase/firestore'
import { db, DEMO_MODE } from '../firebase'
import OctopusMark from './OctopusMark'

const DEMO_LINE = '👑 רונן ל. בפסגה — אבל הלילה הכול יכול להתהפך.\n😅 חצי מכם ניחשו 1-0… יצירתיות, יש לכם?\n🔥 3 משחקים גדולים היום — בהצלחה!'

/** סטורי התמנון's daily AI recap ("Anchor Desk"), generated by the pundit workflow. */
export default function PunditCard() {
  const [text, setText] = useState<string>(DEMO_MODE ? DEMO_LINE : '')

  useEffect(() => {
    if (DEMO_MODE) return
    return onSnapshot(doc(db, 'appState', 'pundit'), (s) => setText((s.data()?.text as string) || ''))
  }, [])

  if (!text) return null
  return (
    <div className="glass" style={{ display: 'flex', alignItems: 'flex-start', gap: 12, padding: '14px 16px', background: 'linear-gradient(135deg, color-mix(in srgb, var(--color-primary) 12%, var(--color-bg-elevated)), var(--color-bg-elevated))' }}>
      <OctopusMark size={40} />
      <div style={{ flex: 1 }}>
        <div style={{ fontSize: 11, color: 'var(--color-text-muted)', fontWeight: 700, marginBottom: 4 }}>🎙️ שולחן הפרשנים · סטורי התמנון</div>
        <div style={{ fontWeight: 600, fontSize: 14, lineHeight: 1.7, whiteSpace: 'pre-line' }}>{text}</div>
      </div>
    </div>
  )
}
